{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibopenai/1.0.0/klibopenai-1.0.0.module",
    "group": "org.jraf.klibopenai",
    "module": "klibopenai",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibopenai-jvm-1.0.0.jar",
          "url": "klibopenai-jvm-1.0.0.jar",
          "size": 110865,
          "sha512": "5662a6a821968ccbf96954dc08dc42cf9af6d5e7620f2a3c4fd12014caf051d0c37c9a0c65d2c98e64716f37c65148d932befe6b1138be2b344b947109b71b49",
          "sha256": "a46978da01f783c1b09f74b2925f795ea6a6a7160894e4de56830af1cf7f0fe1",
          "sha1": "59a693ce6e14e4df10a626d99b81eb539b101da3",
          "md5": "7dd0b7c80ad8f3d8a1ce26a21859d1c7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.10.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.0",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "klibopenai-jvm-1.0.0.jar",
          "url": "klibopenai-jvm-1.0.0.jar",
          "size": 110865,
          "sha512": "5662a6a821968ccbf96954dc08dc42cf9af6d5e7620f2a3c4fd12014caf051d0c37c9a0c65d2c98e64716f37c65148d932befe6b1138be2b344b947109b71b49",
          "sha256": "a46978da01f783c1b09f74b2925f795ea6a6a7160894e4de56830af1cf7f0fe1",
          "sha1": "59a693ce6e14e4df10a626d99b81eb539b101da3",
          "md5": "7dd0b7c80ad8f3d8a1ce26a21859d1c7"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibopenai-jvm-1.0.0-sources.jar",
          "url": "klibopenai-jvm-1.0.0-sources.jar",
          "size": 15694,
          "sha512": "d8b02a7758b1cd7302f5761bf05fce09a17524462a943f51ede3126d1b5326ade425354c404dc1759c96e9fece44a350610d9e7074c4315203360354401e5e6e",
          "sha256": "5eac384744a5424452a32f48fda899979e6ee09736b3c98a8160a1373368e3db",
          "sha1": "479d53c73f60b4fd245890f196d7375e562932ad",
          "md5": "aca589759fb0e05c6431b401671a23af"
        }
      ]
    }
  ]
}
